# Generated by Django 5.2.10 on 2026-02-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
